baseURL = 'https://vrchatapi.github.io/'
languageCode = 'en-us'
title = 'VRChat API Documentation'
description = 'The VRChat API  allows developers to build features that connect them to VRChat.'

disableKinds = ["categories", "tags", "RSS", "taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
    [params.tutorial_categories.general]
    id = "general"
    name = "General"
    order = 0

    [params.tutorial_categories.javascript]
    id = "javascript"
    name = "Node SDK"
    order = 1

    [params.tutorial_categories.python]
    id = "python"
    name = "Python SDK"
    order = 2

    [params.tutorial_categories.java]
    id = "java"
    name = "Java SDK"
    order = 3

    [params.tutorial_categories.dart]
    id = "dart"
    name = "Dart SDK"
    order = 4

    [params.tutorial_categories.rust]
    id = "rust"
    name = "Rust SDK"
    order = 5

    [params.tutorial_categories.csharp]
    id = "csharp"
    name = "C# SDK"
    order = 6

[markup.goldmark.renderer]
    unsafe = true

[markup.highlight]
    noClasses = false